### PR TITLE
Move to using go mod (go 1.11+)

### PR DESCRIPTION
**Pull request by jcmuller**

### CODE REVIEW

**Comment by rafecolton** [comment]
This looks good, thank you for contributing. I'm a little behind on reading about go modules, so let me catch up and I'll get this merged.

**Comment by jcmuller** [comment]
As part of go mods, go libraries will have to use SemVer. Do you mind tagging master (after merging this) something like v1.0.1?

**Comment by rafecolton** [comment]
@jcmuller sure thing. I'll tag it v1.1.0 since it's been in production for a while and a few new features were added.

**Comment by jcmuller** [comment]
@rafecolton rebased the latestaster and updated dependencies.

**Comment by jcmuller** [comment]
@rafecolton nice! Please remember to tag and push v1.1.0

Thanks!

**Comment by rafecolton** [comment]
Yep, done. Decided to go with v1.0.0 since it was the first official tag

**Pull request merged**
