### PR TITLE
Add support for meetings

### PR DESCRIPTION
**Pull request by jcmuller**
Adds support for:
- listing meetings
- getting a meeting
- creating a meeting
- deleting a meeting

As an addition, it also introduces a way to get header only responses from Zoom API V2.

### CODE REVIEW

**Comment by rafecolton** [comment]
@jcmuller this looks really thorough and well documented. Thank you for contributing! It looks like there's a few codeclimate failures that were introduced in this pull request. Will you please see if you can resolve those? After doing so, please @-mention me here, and I will give it another quick once-over and merge.

**Comment by jcmuller** [comment]
@rafecolton Thanks for looking! I checked out the code climate complaints, but I don't really think they're legitimate. The 4 similar blocks of code are all executing `requestV2` with similar (but unique) arguments.  The 4 return limit to `requestV2`.... I guess we could introduce two new functions that themselves return. 

What do you think?

**Comment by rafecolton** [comment]
That sounds right to me. For the code duplication of calling `requestV2`, update the `count_threshold` to 4 in [this line](https://github.com/himalayan-institute/zoom-lib-golang/blob/master/.codeclimate.yml#L18) in `.codeclimate.yml`. For the return limit, see if you can refactor in a way that doesn't look too contrived.

**Comment by jcmuller** [comment]
@rafecolton Done. Had to increase to 5 since there are 4 similar blocks already. No CC issues.

**Pull request merged**
